#!/bin/bash

clear

service_name=camro-backend.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/services/camro-backend/production

service=$service_dir/$service_name

echo Registering camro-backend service for production ...


if [ ! -e "$service" ]; then
	echo
    echo "camro-backend service is not installed"
	echo "Installing camro-backend service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl start $service_name
else 
    echo "camro-backend service is already installed"
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi 
